### ISSUE TITLE
meaning of "start"

### ISSUE THREAD

**Issue by DavidHolmes0** [camillac/holmies#3]
## statement of problem

Your use of "the start" is unclear to me, so it may be unclear to you also.

If it means something like
>the explorer's location at the beginning of a particular execution of the recursive procedure

then your thinking looks good. It would help communication to make that thinking clear in the English. 

On the other hand, if "the start" means something like
>the root call for this problem

then your "statement of problem" fails to apply to the recursive abstraction. You will want to correct that.

You used "the start" in your recursive abstraction also (as one would expect), so make sure the meaning there is also clear, and consistent with the meaning here.

**Comment by lisaye1221** [comment]
Thank you for pointing out the confusion, I changed the "start" to "explorer's current location" which I think is a more concise way of expressing "the explorer's location at the beginning of a particular execution of the recursive procedure."

**Comment by DavidHolmes0** [comment]
Your phrase "explorer's current location" is much, much better than mine. I've added it to my notes for the next time that topic comes up. Thanks.
