### ISSUE TITLE
format pseudocode like code, not English

### ISSUE THREAD

**Issue by DavidHolmes0** [camillac/holmies#4]
Your pseudocode would be easier for me to read if it used indentation, like Python. Check out [Quoting code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) in GitHub's documentation for its version of markdown.

**Comment by lisaye1221** [comment]
Thank you, issue has been resolved, much more pleasant to look at the pseudocode now.

**Comment by DavidHolmes0** [comment]
The if...recursive abstraction looks right to me. It was pretty clear at the end of class that if I just shut up and let Camilla think, with Lisa's help, this would make sense.
