### ISSUE TITLE
snapshot-restore

### ISSUE THREAD

**Issue by DavidHolmes0** [camillac/holmies#7]
Since I'm looking at your pseudocode anyway:

I see where you `drop a wall` appropriately. But I'm also expecting some kind of snapshot-restore pair to get rid of that wall. It will likely take a bit of hard thinking to decideout where to put the snapshot and the restore.

Lot of people will have the challenge of that thinking, so lots of people will be helped by a Piazza post, if that sounds appropriate.

**Comment by camillac** [comment]
We've resolved the issue (added snapshots and restores). Thanks for the feedback!
